-- =============================================
-- Storage Policies for Photos Bucket
-- ВАЖНО: Этот SQL требует прав суперпользователя и обычно не работает
-- Используй UI Dashboard для создания политик (см. SUPABASE_SETUP.md)
-- =============================================
--
-- Если у тебя есть права суперпользователя, можешь выполнить этот SQL:
--
-- Enable RLS on storage.objects (if not already enabled)
-- ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
--
-- Policy 1: Allow authenticated users to upload photos to their own folder
-- CREATE POLICY "Allow authenticated uploads" ON storage.objects
--   FOR INSERT
--   TO authenticated
--   WITH CHECK (
--     bucket_id = 'photos' AND
--     (storage.foldername(name))[1] = (auth.uid())::text
--   );
--
-- Policy 2: Allow public read access to all photos
-- CREATE POLICY "Allow public read" ON storage.objects
--   FOR SELECT
--   TO public
--   USING (bucket_id = 'photos');
--
-- Policy 3: Allow users to delete their own photos
-- CREATE POLICY "Allow delete own photos" ON storage.objects
--   FOR DELETE
--   TO authenticated
--   USING (
--     bucket_id = 'photos' AND
--     (storage.foldername(name))[1] = (auth.uid())::text
--   );
--
-- Policy 4: Allow users to update their own photos (for future use)
-- CREATE POLICY "Allow update own photos" ON storage.objects
--   FOR UPDATE
--   TO authenticated
--   USING (
--     bucket_id = 'photos' AND
--     (storage.foldername(name))[1] = (auth.uid())::text
--   )
--   WITH CHECK (
--     bucket_id = 'photos' AND
--     (storage.foldername(name))[1] = (auth.uid())::text
--   );
--
-- =============================================
-- ИНСТРУКЦИИ ДЛЯ UI DASHBOARD:
-- =============================================
-- 1. Перейди в Storage → photos → Policies
-- 2. Нажми "New Policy"
-- 3. Создай политики согласно инструкциям в SUPABASE_SETUP.md
-- =============================================
