-- =============================================
-- Seed data: Challenges (челленджи)
-- Run this in Supabase SQL Editor AFTER running supabase-schema.sql
-- =============================================

INSERT INTO challenges (title, points, category) VALUES

-- Home / Interior
('Snap a wall shelf bracket', 1, 'home'),
('Snap a picture hanging on the wall', 1, 'home'),
('Snap a wall clock', 1, 'home'),
('Snap a ceiling lamp', 2, 'home'),
('Snap a baseboard', 1, 'home'),
('Snap a door frame', 1, 'home'),
('Snap a window sill', 1, 'home'),
('Snap a radiator', 2, 'home'),
('Snap a light switch', 1, 'home'),
('Snap a door handle', 1, 'home'),
('Snap an electrical socket', 1, 'home'),
('Snap a smoke detector on ceiling', 2, 'home'),
('Snap an air vent grille', 1, 'home'),
('Snap a curtain rod', 1, 'home'),
('Snap floor tiles pattern close-up', 1, 'home'),
('Snap a door hinge', 1, 'home'),
('Snap a wall mirror', 1, 'home'),
('Snap a coat hook on wall', 1, 'home'),

-- Kitchen
('Snap a kettle', 1, 'kitchen'),
('Snap a frying pan', 1, 'kitchen'),
('Snap a cooking pot', 1, 'kitchen'),
('Snap a set of kitchen knives', 1, 'kitchen'),
('Snap a fork', 1, 'kitchen'),
('Snap a toaster', 2, 'kitchen'),
('Snap a coffee machine', 2, 'kitchen'),
('Snap a microwave oven', 2, 'kitchen'),
('Snap a cutting board', 1, 'kitchen'),
('Snap a wooden spoon', 1, 'kitchen'),
('Snap a spatula', 1, 'kitchen'),
('Snap a whisk', 1, 'kitchen'),
('Snap a kitchen scale', 2, 'kitchen'),
('Snap a blender', 2, 'kitchen'),
('Snap a spice jar', 1, 'kitchen'),
('Snap a salt shaker', 1, 'kitchen'),
('Snap a pepper grinder', 1, 'kitchen'),
('Snap a colander', 1, 'kitchen'),
('Snap a grater', 1, 'kitchen'),
('Snap an apron hanging', 1, 'kitchen'),

-- Food (чёткие одиночные объекты)
('Snap a banana', 1, 'food'),
('Snap an apple', 1, 'food'),
('Snap an orange', 1, 'food'),
('Snap a lemon', 1, 'food'),
('Snap a tomato', 1, 'food'),
('Snap a cucumber', 1, 'food'),
('Snap a carrot', 1, 'food'),
('Snap an onion', 1, 'food'),
('Snap a potato', 1, 'food'),
('Snap a garlic bulb', 1, 'food'),
('Snap a bell pepper', 1, 'food'),
('Snap an avocado', 1, 'food'),
('Snap a single egg', 1, 'food'),
('Snap a milk carton', 1, 'food'),
('Snap a yogurt cup', 1, 'food'),
('Snap a butter pack', 1, 'food'),
('Snap a piece of cheese', 1, 'food'),
('Snap a chocolate bar', 1, 'food'),
('Snap a pack of cookies', 1, 'food'),
('Snap a bag of chips', 1, 'food'),
('Snap a jar of honey', 1, 'food'),
('Snap a jar of jam', 1, 'food'),
('Snap a ketchup bottle', 1, 'food'),
('Snap a mayonnaise jar', 1, 'food'),
('Snap a pear', 1, 'food'),
('Snap kiwi fruit', 1, 'food'),
('Snap a bunch of grapes', 1, 'food'),
('Snap strawberries', 1, 'food'),

-- Street / Outdoor (универсальные, без привязки к стране)
('Snap a public mailbox', 2, 'street'),
('Snap a house number on building', 1, 'street'),
('Snap a street name sign', 1, 'street'),
('Snap any traffic sign', 1, 'street'),
('Snap a no-parking sign', 1, 'street'),
('Snap a manhole cover', 1, 'street'),
('Snap a street lamp pole', 1, 'street'),
('Snap a public bench', 1, 'street'),
('Snap a glass recycling container', 2, 'street'),
('Snap a recycling bin', 1, 'street'),
('Snap a bicycle attached to a stand', 1, 'street'),
('Snap a parking meter', 2, 'street'),
('Snap a bus stop sign', 2, 'street'),
('Snap an electricity utility box', 2, 'street'),
('Snap a curbstone edge', 1, 'street'),
('Snap a flower box on window sill', 2, 'street'),
('Snap a speed bump', 2, 'street'),
('Snap a fire hydrant', 2, 'street'),

-- Technology
('Snap a computer mouse', 1, 'tech'),
('Snap a keyboard', 1, 'tech'),
('Snap a laptop', 2, 'tech'),
('Snap a smartphone', 1, 'tech'),
('Snap a phone charger plugged in', 1, 'tech'),
('Snap a power strip', 1, 'tech'),
('Snap a Wi-Fi router', 2, 'tech'),
('Snap a smart speaker', 2, 'tech'),
('Snap wireless earbuds case', 1, 'tech'),

-- Bathroom
('Snap a toothbrush', 1, 'bathroom'),
('Snap a toothpaste tube', 1, 'bathroom'),
('Snap a shampoo bottle', 1, 'bathroom'),
('Snap a shower gel bottle', 1, 'bathroom'),
('Snap a towel hanging', 1, 'bathroom'),
('Snap a toilet paper roll', 1, 'bathroom'),
('Snap a bar of soap', 1, 'bathroom'),
('Snap a hairdryer', 2, 'bathroom'),

-- Bedroom
('Snap a pillow', 1, 'bedroom'),
('Snap an alarm clock', 1, 'bedroom'),
('Snap a bedside lamp', 1, 'bedroom'),
('Snap a clothes hanger', 1, 'bedroom'),

-- Cleaning
('Snap a broom', 1, 'cleaning'),
('Snap a dustpan', 1, 'cleaning'),
('Snap a roll of trash bags', 1, 'cleaning'),
('Snap a dishwashing sponge', 1, 'cleaning'),
('Snap a bottle of dish soap', 1, 'cleaning'),

-- Personal / Everyday
('Snap a wrist watch', 1, 'personal'),
('Snap a pair of sunglasses', 1, 'personal'),
('Snap house slippers', 1, 'personal'),
('Snap a pair of sneakers', 1, 'personal'),
('Snap a pen', 1, 'daily'),
('Snap a notebook', 1, 'daily'),
('Snap a TV remote control', 1, 'daily'),
('Snap a plastic bottle', 1, 'daily'),
('Snap a house key', 1, 'daily'),

-- Office / Work
('Snap a stapler', 1, 'office'),
('Snap a hole punch', 1, 'office'),
('Snap a desk phone', 2, 'office'),
('Snap an office chair', 2, 'office'),
('Snap a desk drawer', 1, 'office'),
('Snap a whiteboard marker', 1, 'office'),
('Snap a desk calendar', 1, 'office'),
('Snap a printer', 2, 'office'),
('Snap a scanner', 2, 'office'),
('Snap a desk fan', 2, 'office'),
('Snap a nameplate on desk', 1, 'office'),
('Snap a filing cabinet drawer', 1, 'office'),
('Snap a paper tray', 1, 'office'),
('Snap a desk lamp', 1, 'office'),
('Snap a mouse pad', 1, 'office'),
('Snap a highlighter pen', 1, 'office'),
('Snap a sticky note pad', 1, 'office'),
('Snap a tape dispenser', 1, 'office'),
('Snap a coffee mug on desk', 1, 'office'),
('Snap a water cooler bottle', 2, 'office'),
('Snap an office plant pot', 1, 'office'),
('Snap a power outlet strip under desk', 1, 'office'),
('Snap a keyboard tray', 1, 'office'),
('Snap a monitor arm', 2, 'office')

ON CONFLICT DO NOTHING;
